"""1-Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""
n1,n2=1,2
list1=[n1,n2]
while True:
    n3=n1+n2
    if n3<4000000:
        list1.append(n3)
        n1=n2
        n2=n3
    else:
        break
print(list1)
add=0
for num in list1:  
    if num%2==0:
        add=add+num
print("The sum of the even-valued terms is",add)

